Added common code module for scripts (_common).
--HG--
branch : dev

diff --git a/bin/dummy b/bin/dummy
--- a/bin/dummy
+++ b/bin/dummy
@@ -14,17 +14,15 @@ mydir="${PWD%/}"
 cd "$current_wd"
 ########################################################################
 
-# load configurations and helper functions
+# load common code
 
-BASE_DIR="$mydir"
-CONFIG_DIR="/etc/audit"
-CONFIG="${CONFIG_DIR}/run_audit.conf"
-UTILS="${BASE_DIR}/utils"
+AUDIT_COMMON="${mydir}/_common"
+if [ ! -f "$AUDIT_COMMON" ]; then
+    printf >&2 "### Audit common code module not found: $AUDIT_COMMON\n"
+    exit 1
+fi
+. "$AUDIT_COMMON"
 
-. "$CONFIG"
-. "$UTILS"
-
-check_root_user
 
 # output message
 
diff --git a/bin/lsat b/bin/lsat
--- a/bin/lsat
+++ b/bin/lsat
@@ -16,24 +16,19 @@ cd "$current_wd"
 
 PATH=/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
 
-# load configurations and helper functions
+# load common code
 
-BASE_DIR="$mydir"
-CONFIG_DIR="/etc/audit"
-CONFIG="${CONFIG_DIR}/run_audit.conf"
-UTILS="${BASE_DIR}/utils"
-
-. "$CONFIG"
-. "$UTILS"
-
-check_root_user
+AUDIT_COMMON="${mydir}/_common"
+if [ ! -f "$AUDIT_COMMON" ]; then
+    printf >&2 "### Audit common code module not found: $AUDIT_COMMON\n"
+    exit 1
+fi
+. "$AUDIT_COMMON"
 
 # run lsat audit
 
 SCANNER=$(which lsat)
 LOGFILE="${LOG_DIR:-/var/log/audit}/lsat.out"
-
-DIVIDER="########################################################################"
 
 makedir "$(dirname $LOGFILE)"
 
diff --git a/bin/rkhunter b/bin/rkhunter
--- a/bin/rkhunter
+++ b/bin/rkhunter
@@ -6,8 +6,6 @@
 # * created: 2012-02-05 Kevin Chan <kefin@makedostudio.com>
 # * updated: 2014-11-01 kchan
 
-PATH=/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
-
 ########################################################################
 myname="${0##*/}"
 current_wd=$PWD
@@ -16,17 +14,16 @@ mydir="${PWD%/}"
 cd "$current_wd"
 ########################################################################
 
-# load configurations and helper functions
+PATH=/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
 
-BASE_DIR="$mydir"
-CONFIG_DIR="/etc/audit"
-CONFIG="${CONFIG_DIR}/run_audit.conf"
-UTILS="${BASE_DIR}/utils"
+# load common code
 
-. "$CONFIG"
-. "$UTILS"
-
-check_root_user
+AUDIT_COMMON="${mydir}/_common"
+if [ ! -f "$AUDIT_COMMON" ]; then
+    printf >&2 "### Audit common code module not found: $AUDIT_COMMON\n"
+    exit 1
+fi
+. "$AUDIT_COMMON"
 
 # run rkunter audit
 
diff --git a/bin/run_audit b/bin/run_audit
--- a/bin/run_audit
+++ b/bin/run_audit
@@ -63,41 +63,20 @@ EOF
 }
 
 ########################################################################
-# run audit scripts
 
-# load utilities and configurations
+# load common code
 
-VERBOSE=1
-DEBUG=0
-
-BASE_DIR="$mydir"
-CONFIG_DIR="/etc/audit"
-CONFIG="${CONFIG_DIR}/run_audit.conf"
-UTILS="${BASE_DIR}/utils"
-DEFAULT_LOG_DIR="/var/log/audit"
-
-DIVIDER="########################################################################"
-
-errors=0
-dry_run=0
-email_report=1
-
-[ ! -f "$UTILS" ] && error "Utilities module not found: $UTILS"
-. "$UTILS"
-
-if [ ! -f "$CONFIG" ]; then
-    cat <<EOF
-### Configuration file not found: $CONFIG
-# You must have a configuration file ($CONFIG)
-# for this script to run. A configuration file template is in
-# $CONFIG_DIR. Make a copy of the template and rename it as
-# $CONFIG, then run this script again.
-# Type '$0 --help' for usage informaton.
-EOF
+AUDIT_COMMON="${mydir}/_common"
+if [ ! -f "$AUDIT_COMMON" ]; then
+    printf >&2 "### Audit common code module not found: $AUDIT_COMMON\n"
     exit 1
 fi
-. "$CONFIG"
+. "$AUDIT_COMMON"
 
+
+# set vars and define functions
+
+email_report=1
 
 # functions to test if sub-script exists and is executable
 # * is_executable does minimal filtering and checks if script
@@ -190,6 +169,8 @@ run_script()
     fi
 
     elog "# done."
+    elog ""
+
     return $exit_status
 }
 
