Refactored utils and audit scripts.
--HG--
branch : dev

diff --git a/bin/lsat b/bin/lsat
--- a/bin/lsat
+++ b/bin/lsat
@@ -53,6 +53,8 @@ run_lsat()
     cd "$_current_wd"
 }
 
-[ "X$LSAT" != "X" -a -x "$LSAT" ] \
-    && run_tool "lsat" "run_lsat" \
-    || error "unable to execute command: lsat"
+if [ "X$LSAT" != "X" ] && [ -x "$LSAT" ]; then
+    run_tool "lsat" "run_lsat" || exit 1
+else
+    error "unable to execute command: lsat"
+fi
diff --git a/bin/lynis b/bin/lynis
--- a/bin/lynis
+++ b/bin/lynis
@@ -43,6 +43,8 @@ run_lynis()
     fi
 }
 
-[ "X$LYNIS" != "X" -a -x "$LYNIS" ] \
-    && run_tool "lynis" "run_lynis" \
-    || error "unable to execute command: lynis"
+if [ "X$LYNIS" != "X" ] && [ -x "$LYNIS" ]; then
+    run_tool "lynis" "run_lynis" || exit 1
+else
+    error "unable to execute command: lynis"
+fi
diff --git a/bin/rkhunter b/bin/rkhunter
--- a/bin/rkhunter
+++ b/bin/rkhunter
@@ -41,6 +41,8 @@ run_rkhunter()
 
 makedir "$(dirname $RKHUNTER_LOGFILE)"
 
-[ "X$RKHUNTER" != "X" -a -x "$RKHUNTER" ] \
-    && run_tool "rkhunter" "run_rkhunter" \
-    || error "unable to execute command: rkhunter"
+if [ "X$RKHUNTER" != "X" ] && [ -x "$RKHUNTER" ]; then
+    run_tool "rkhunter" "run_rkhunter" || exit 1
+else
+    error "unable to execute command: rkhunter"
+fi
