Cleaned up audit scripts (took out debug messages).
--HG--
branch : dev

diff --git a/bin/lynis b/bin/lynis
--- a/bin/lynis
+++ b/bin/lynis
@@ -35,6 +35,12 @@ LOGFILE="${LOG_DIR:-/var/log/audit}/lynis.log"
 run_lynis()
 {
     "$LYNIS" -c -Q --auditor "$AUDITOR" --logfile "$LOGFILE" --cronjob
+    if [ -f "$LOGFILE" ]; then
+        cat "$LOGFILE"
+    else
+        printf >&2 "### log file not found: $LOGFILE\n"
+        return 1
+    fi
 }
 
 makedir "$(dirname $LOGFILE)"
diff --git a/bin/rkhunter b/bin/rkhunter
--- a/bin/rkhunter
+++ b/bin/rkhunter
@@ -34,8 +34,13 @@ LOGFILE="${LOG_DIR:=/var/log/audit}/rkhunter.log"
 
 run_rkhunter()
 {
-    "$RKHUNTER" --cronjob --logfile "$LOGFILE" || return 1
-    cat "$LOGFILE"
+    "$RKHUNTER" --cronjob --logfile "$LOGFILE"
+    if [ -f "$LOGFILE" ]; then
+        cat "$LOGFILE"
+    else
+        printf >&2 "### log file not found: $LOGFILE\n"
+        return 1
+    fi
 }
 
 makedir "$(dirname $LOGFILE)"
